---
title: "Andrea - Assessment 3"
author: "Andrea Botes"
date: "04/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(rtweet)
library(tidytext)
library(dplyr)
library(tidyr)
```

## Data import

Collect tweets about Luna

```{r}

luna_tweets<-search_tweets(
  q="luna",
  n=50,
  include_rts = TRUE,
  lang="en",
  retryonratelimit = TRUE
)

```

Cleaner version:

```{r}
#look at first 10 obs
luna_tweets%>%
  head(10)

#look at structure
luna_tweets%>%
  str()
  
luna_short<-luna_tweets %>%
  select(user_id , screen_name , created_at , text , favorite_count, retweet_count, urls_expanded_url, hashtags, mentions_screen_name, location)

luna_short%>%write_csv("luna_short_04_06_2022.csv")
luna_tweets<-read_csv("luna_short_04_06_22.csv")
```

# Part 3: Topic Modeling & visualisation
  
## Preprocess text from dataset to tidy text & convert to DocumenttermMatric

### Clean up dataset text

```{r}
tidy_luna <- luna_short %>%
  mutate(text) %>%
  unnest_tokens(word , text) %>%
  anti_join(get_stopwords()) %>%
  filter(!is.na(word) & !grepl("[^A-Za-z]" , word) & word != "https" & word !="na")

tidy_luna %>%
  count(word , sort = TRUE)

```


```{r}
head(tidy_luna$word)

#remove stop words from list of words

cleaned_tidy_luna <- tidy_luna %>%
  anti_join(stop_words)
head(cleaned_tidy_luna)

head(tidy_luna$word)
```

# top 10 most commonly used words

```{r}
cleaned_tidy_luna %>%
  count(word, sort = TRUE) %>%
  top_n(10) %>%
  mutate(word = reorder(word, n)) %>%
  ggplot(aes(x = word , y= n)) +
  geom_col() +
  xlab(NULL) +
  coord_flip() +
  theme_classic() +
  labs(x = "Count" , 
       y = "Unique words" , 
       title = "Unique word counts found in #luna tweets")

```

Sentiment analysis

```{r}

```
